#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-asn1crypto
Version  : 1.5.0
Release  : 59
URL      : https://files.pythonhosted.org/packages/a7/ae/1280022d918be3aabd1ca89ecb87714743d1c9e1df5695e302dc05595fe8/asn1crypto-1.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a7/ae/1280022d918be3aabd1ca89ecb87714743d1c9e1df5695e302dc05595fe8/asn1crypto-1.5.0.tar.gz
Summary  : Fast ASN.1 parser and serializer with definitions for private keys, public keys, certificates, CRL, OCSP, CMS, PKCS#3, PKCS#7, PKCS#8, PKCS#12, PKCS#5, X.509 and TSP
Group    : Development/Tools
License  : MIT
Requires: pypi-asn1crypto-python = %{version}-%{release}
Requires: pypi-asn1crypto-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# asn1crypto
A fast, pure Python library for parsing and serializing ASN.1 structures.

%package python
Summary: python components for the pypi-asn1crypto package.
Group: Default
Requires: pypi-asn1crypto-python3 = %{version}-%{release}

%description python
python components for the pypi-asn1crypto package.


%package python3
Summary: python3 components for the pypi-asn1crypto package.
Group: Default
Requires: python3-core
Provides: pypi(asn1crypto)

%description python3
python3 components for the pypi-asn1crypto package.


%prep
%setup -q -n asn1crypto-1.5.0
cd %{_builddir}/asn1crypto-1.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646835306
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
